//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_3.baseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PracticaS13Entities : DbContext
    {
        public PracticaS13Entities()
            : base("name=PracticaS13Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonos> Abonos { get; set; }
        public virtual DbSet<Principal> Principal { get; set; }
    
        public virtual ObjectResult<ObtenerCompras_Result> ObtenerCompras()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerCompras_Result>("ObtenerCompras");
        }
    
        public virtual ObjectResult<ObtenerComprasPendientes_Result> ObtenerComprasPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerComprasPendientes_Result>("ObtenerComprasPendientes");
        }
    
        public virtual ObjectResult<Nullable<decimal>> ObtenerSaldoCompra(Nullable<long> id_Compra)
        {
            var id_CompraParameter = id_Compra.HasValue ?
                new ObjectParameter("Id_Compra", id_Compra) :
                new ObjectParameter("Id_Compra", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("ObtenerSaldoCompra", id_CompraParameter);
        }
    
        public virtual int RegistrarAbono(Nullable<long> id_Compra, Nullable<decimal> monto)
        {
            var id_CompraParameter = id_Compra.HasValue ?
                new ObjectParameter("Id_Compra", id_Compra) :
                new ObjectParameter("Id_Compra", typeof(long));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarAbono", id_CompraParameter, montoParameter);
        }
    
        public virtual ObjectResult<ConsultarCompras_Result> ConsultarCompras()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarCompras_Result>("ConsultarCompras");
        }
    }
}
